# Generated by Django 4.1.7 on 2023-03-27 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owf_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.BigIntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('stack_context', models.CharField(blank=True, default=uuid.uuid4, max_length=200, unique=True)),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('descriptor_url', models.CharField(blank=True, max_length=2083, null=True)),
                ('unique_widget_count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('default_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_stack_group', to='owf_groups.owfgroup')),
            ],
            options={
                'db_table': 'stack',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StackGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owf_groups.owfgroup')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
            options={
                'db_table': 'stack_groups',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='stack',
            name='groups',
            field=models.ManyToManyField(through='stacks.StackGroups', to='owf_groups.owfgroup'),
        ),
        migrations.AddField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='stackgroups',
            constraint=models.UniqueConstraint(fields=('group', 'stack'), name='unique_stack_groups'),
        ),
    ]
